### PR TITLE
Feature/component ids

### PR DESCRIPTION
**Pull request by ktraunmueller**
I think we more or less agree that the introduction of (optional) identifiers for `Component`s and their associated view controllers would be beneficial (e.g., for identifying view controllers in a deep linking implementation).

Here's a very straightforward suggestion on how this might look like.

### CODE REVIEW

**Comment by ChristianOrgler** [comment]
I agree that the `id` should be on the top level in the json. However if this is optional it kind of looks like it would fit better in the `ComponentMeta` as it can be there but doesn't have to necessarily.

If we would put it in the `ComponentMeta` it looks a bit cleaner. (duh, good comment fuzi)
Also not sure if we need to have it "top level" in the `Component` code. As we don't gain anything putting it in the builder function itself. We kind of need it later on anyway right?

Any opinions @endscha , @mathiasAichinger

**Comment by AndreasThenn** [comment]
I agree, if we choose *top level* then it may be better to have it mandatory like `type`. If it is optional, then it could also go into the `ComponentMeta`.

**Comment by ktraunmueller** [comment]
Looking at the code, I don't like the interface bloat this brings with it. 

I would now actually prefer having the `id` in the meta dictionary. This would match well with the optionality of this piece of information, it would be the most flexible solution, and we don't have to bloat the interfaces.

**Comment by ChristianOrgler** [comment]
Agree, can you change the implementation then? Still having a key constant is a good idea imho.

**Comment by ktraunmueller** [comment]
We discussed the issue and came to the conclusion that
- we'll call this simply `id`
- this `id` is optional, and should should be part of the meta dictionary, not a top level item

I'll close this pull request, and open another one that documents the intended use of this meta field in the JSON schema guide.

**Pull request closed without merging**
